In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline

#If you have any confusion matrix then see this link:-
# https://www.youtube.com/watch?v=0kPRaYSgblM&fbclid=IwAR0mhZAzD1IindpFnTUfLV69MwLXBbwhls8q7st_1jYws-7Qtyjm2FuXYpU

# Section 1
# Word Count - CountVectorizer 

Lets gets back to our Naive Bayes Classifier what we basically doing is that we will actually count the number of times a particular word is coming in that partcular category.

Then we find the probability and then we classify using Naive Bayes.

But how you will make a machine to actually count the number of words.

So what it basically it does is (for example  let's assume you have a big sentence) that it will give a particular unique number to each of unique words then after that it will count that how many times that a particular is coming it is not going to actually check that text but instead it will give a number to that particular text then it will count how that number is repeating.

So, that giving a unique value to each and every word that is done by fit() method. It is under count-vectorizer class. 
we can do this collectively by using the method fit_transform()

And then counting the number of times that particular number is comming is done by transform method

                (you can see my .pdf for more info...)

In [12]:
# Demo code to understand CountVectorizer

from sklearn.feature_extraction.text import CountVectorizer
# text = ["I am manjeet raj lakshman",
#        "My college name is Army Institute of Technology",
#        "Demo code to understand CountVectorizer"]
text = ["The quick brown fox jump over the lazy dog",
       "The dog",
       "The fox"]
vector = CountVectorizer()
vector.fit(text) # Learn a vocabulary dictionary of all
                 # tokens in the row documents.
    
print("print Vocabulary : " +str(vector.vocabulary_))

vector.get_feature_names()
print("feature name : " +str(vector.get_feature_names()))

counts = vector.transform(text)
print("The shape of count  : " +str(counts.shape)) #in it's shape 3 is denoting the columnof the dict(or number of sample)
#and 17 is denoting the number of column i.e number of feature

print("Printing counts : "+str(counts.toarray()))



CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

print Vocabulary : {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jump': 3, 'over': 5, 'lazy': 4, 'dog': 1}


['brown', 'dog', 'fox', 'jump', 'lazy', 'over', 'quick', 'the']

feature name : ['brown', 'dog', 'fox', 'jump', 'lazy', 'over', 'quick', 'the']
The shape of count  : (3, 8)
Printing counts : [[1 1 1 1 1 1 1 2]
 [0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]]


# Section 2
# Term Frequency Inverse Document Frequency

In previous (step2/section1) we have counted the number of
words but it has one issue.

what is the issue?
-for example the word like 'though' it will come as so
many times but it's large count doesn't make any sense in
the classification of the documents.

So what the 'term frequency' and 'Inverse Document' does is?
-Term Frequency :- it means number of times that 
                   particular word is coming

                   
-Inverse Document :- it will actually give the weight
                     that how much it is important for 
                     the classification.
                     
So the word like 'though will get the minimum weight
for the classification

This can be done by using one of the class of scikit-learn that is = sklearn.feature_extraction.text.TfidfVectorizer
in that we will use the method fit_transform()

                (you can see in .pdf file for info...)

In [13]:
# Demo code to understand TfidfTransformer

from sklearn.feature_extraction.text import TfidfTransformer
# create the transform method  
vectorizer = TfidfTransformer()

vectorizer.fit(counts) #Learning frequency of all features
print("Learning frequency of all features : " +str(vectorizer.idf_))
#you can see word like "The" is getting least weight

freq = vectorizer.transform(counts) # Transforming the matrix 
#based on the learnt frequencies or weight of all feature(count matrix that i have learnt before)
print("Transforming the matrix based on the learnt frequencies or weight : ")
freq.toarray()

TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True)

Learning frequency of all features : [1.69314718 1.28768207 1.28768207 1.69314718 1.69314718 1.69314718
 1.69314718 1.        ]
Transforming the matrix based on the learnt frequencies or weight : 


array([[0.36388646, 0.27674503, 0.27674503, 0.36388646, 0.36388646,
        0.36388646, 0.36388646, 0.42983441],
       [0.        , 0.78980693, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.61335554],
       [0.        , 0.        , 0.78980693, 0.        , 0.        ,
        0.        , 0.        , 0.61335554]])

# Section 3
# Naive Bayes Classifier

In [23]:
import sklearn.datasets as skd
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
news_train = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/train',categories=categories,encoding='ISO-8859-1')
news_test = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/test',categories=categories,encoding='ISO-8859-1')

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
x_train_tf = count_vect.fit_transform(news_train.data)

from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_tf)

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train_tfidf,news_train.target)

In [24]:
docs_new = ['God is love','OpenGL on the CPU is fast']
x_new_counts = count_vect.transform(docs_new) #here i'm not using fit_transfom()
# why, because fit() is used for learning and i have already 
# used before to learn the module now what i have to do is 
# whatever the sentences is comming for prediction i have to
# transform it based on my learning that i have already learnt
# before and learning is done by fit().So now only i need to
# transform the incomming sentences. that's why i am not using
# fit_transfom() method
x_new_tfidf = tfidf_transformer.transform(x_new_counts) # same reason
# why i am only using transform(),not fit().
predicted = clf.predict(x_new_tfidf)

In [25]:
predicted #here 3 means 'God is love' is belongs to 4th categories i.e soc.religion.christian
# and 1 means 'OpenGL on the CPU is fast' belongs to 2nd category i.e comp.graphics


array([3, 1])

# Section 4
# Result

Now we have to deail with the test data:-
- Take you new test data
- Again CountVectorize it
- Use TD IDF transformer
- Then predict it using MultinomialNB()
- Analyse the result
- METRICS.Classification_report()
  .Precision    .micro-avg
  .Recall       .macro-avg
  .F1-score     .weighted-avg

In [27]:
x_test_tf = count_vect.transform(news_test.data)
x_test_tf.shape
x_test_tfidf = tfidf_transformer.transform(x_test_tf)

predicted = clf.predict(x_test_tfidf)

(1502, 35788)

In [28]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(news_test.target,predicted))
print(metrics.classification_report(news_test.target,predicted,target_names=news_test.target_names))

metrics.confusion_matrix(news_test.target,predicted)

Accuracy :  0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]])