In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
%matplotlib inline

Steps in which i impliment this

step1 : Import Data
step2 : Word Count - CountVectorizer
step3 : Term Frequency Inverse Document Frequency
step4 : Naive Bayes Classifier
step5 : Result

In [2]:
import sklearn.datasets as skd

# Step1 : Importing Data offline

In [3]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
news_train = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/train',categories=categories,encoding='ISO-8859-1')
news_test = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/test',categories=categories,encoding='ISO-8859-1')

In [4]:
#After loading the data, the variable news_test and news_train
#stores as a dictionary
news_train.keys()
news_train['target'] #here just i'm accessing the target
news_train['target_names']
news_train.target_names

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])

array([2, 1, 3, ..., 1, 1, 2])

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

# Step : 2 Word Count - CountVectorizer

See Section-1 of Rough work for Text classification .ipynb file

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
x_train_tf = count_vect.fit_transform(news_train.data)
x_train_tf.shape

(2257, 35788)

# Step3 : Term Frequency Inverse Document Frequency

See Section-2 of Rough work for Text classification .ipynb file

In [6]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_tf)
x_train_tfidf.shape

(2257, 35788)

# step4 : Naive Bayes Classifier

In [7]:
#here we are using Multinomial Naive Bayes Classifier

#sklearn already has inbuilt Multinomial Naive Bayes Classifier package

#Using this package we can directly train our model with the
#matrix obtained from TfidTransformer

from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(x_train_tfidf,news_train.target) #parameter is data and it's label

# see section-3 for the demo that how it is doing
# also see my .pdf file of this part.

# step5 : Result

see section 4 of Rough work for Text classification .ipynb file

In [12]:
x_test_tf = count_vect.transform(news_test.data)
x_test_tf.shape
x_test_tfidf = tfidf_transformer.transform(x_test_tf)
predicted = clf.predict(x_test_tfidf)

(1502, 35788)

In [15]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(news_test.target,predicted))
print(metrics.classification_report(news_test.target,predicted,target_names=news_test.target_names))

metrics.confusion_matrix(news_test.target,predicted)

Accuracy :  0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]])

# Using Pipline Line concept
Here we are doing same thing which is done by us in the above

In [16]:
import sklearn.datasets as skd

categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']
news_train = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/train',categories=categories,encoding='ISO-8859-1')
news_test = skd.load_files('/home/manjeet/Videos/Documentation/ML-algo/Text-classification-using-Naive-Bayes/data/test',categories=categories,encoding='ISO-8859-1')

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

text_clf = Pipeline([('vect', TfidfVectorizer()), 
                      ('clf', MultinomialNB()) ])

# train the model
text_clf.fit(news_train.data, news_train.target)
# Predict the test cases
predicted = text_clf.predict(news_test.data)

from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np

print('Accuracy achieved is ' + str(np.mean(predicted == news_test.target)))
print(metrics.classification_report(news_test.target, predicted, target_names=news_test.target_names)),
metrics.confusion_matrix(news_test.target, predicted)


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

Accuracy achieved is 0.8348868175765646
                        precision    recall  f1-score   support

           alt.atheism       0.97      0.60      0.74       319
         comp.graphics       0.96      0.89      0.92       389
               sci.med       0.97      0.81      0.88       396
soc.religion.christian       0.65      0.99      0.78       398

             micro avg       0.83      0.83      0.83      1502
             macro avg       0.89      0.82      0.83      1502
          weighted avg       0.88      0.83      0.84      1502



(None,)

array([[192,   2,   6, 119],
       [  2, 347,   4,  36],
       [  2,  11, 322,  61],
       [  2,   2,   1, 393]])

#                              Done